production:
  octokit_access_token: <%= ENV['OCTOKIT_ACCESS_TOKEN'] %>

development:
  octokit_access_token: <%= ENV['OCTOKIT_ACCESS_TOKEN'] %>

test:
  octokit_access_token: <%= ENV['OCTOKIT_ACCESS_TOKEN'] %>
